# Generated by Django 3.2 on 2021-05-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='date_of_release',
        ),
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='computer',
            name='name',
            field=models.TextField(default='', max_length=50, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='hdd',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='powerblock',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='ram',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='case',
            name='color',
            field=models.TextField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='case',
            name='computer_id',
            field=models.ManyToManyField(related_name='related_Case', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='depth',
            field=models.PositiveIntegerField(verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='case',
            name='form_factor',
            field=models.TextField(max_length=50, verbose_name='Форм-фактор'),
        ),
        migrations.AlterField(
            model_name='case',
            name='height',
            field=models.PositiveIntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='case',
            name='manufacturer',
            field=models.TextField(max_length=50, verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='case',
            name='material',
            field=models.TextField(max_length=50, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='case',
            name='max_size_of_motherboard',
            field=models.TextField(verbose_name='Максимальный размер материнской платы'),
        ),
        migrations.AlterField(
            model_name='case',
            name='model',
            field=models.TextField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='case',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Год релиза'),
        ),
        migrations.AlterField(
            model_name='case',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='CPU_cores',
            field=models.PositiveIntegerField(verbose_name='Количество ядер'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='CPU_series',
            field=models.TextField(max_length=50, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='CPU_socket',
            field=models.TextField(max_length=50, verbose_name='Сокет'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='CPU_speed',
            field=models.PositiveIntegerField(verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='CPU_turbo_speed',
            field=models.PositiveIntegerField(verbose_name='Максимальная тактовая частота'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='L3_Cache',
            field=models.PositiveIntegerField(verbose_name='Кэш'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='computer_id',
            field=models.ManyToManyField(related_name='related_CPU', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='manufacturer',
            field=models.TextField(max_length=50, verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Год релиза'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='threads',
            field=models.PositiveIntegerField(verbose_name='Количество потоков'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='unlocked_multiplier',
            field=models.BooleanField(verbose_name='Возможность для разгона'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='VRAM',
            field=models.PositiveIntegerField(verbose_name='Видеопамять'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='chipset',
            field=models.TextField(max_length=50, verbose_name='Чипсет'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='computer_id',
            field=models.ManyToManyField(related_name='related_GPU', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='effective_speed',
            field=models.PositiveIntegerField(verbose_name='Эффетивная частота'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='manufacturer',
            field=models.TextField(max_length=50, verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='recommended_power',
            field=models.PositiveIntegerField(verbose_name='Рекомендуемая можность БП'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Год релиза'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='vram_type',
            field=models.TextField(max_length=50, verbose_name='Тип видеопамяти'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='cache',
            field=models.PositiveIntegerField(verbose_name='Кэш'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Емкость'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='computer_id',
            field=models.ManyToManyField(related_name='related_HDD', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='form_factor',
            field=models.TextField(max_length=50, verbose_name='Форм-фактор'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='interface_type',
            field=models.TextField(max_length=50, verbose_name='Тип интерфейса'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='manufacturer',
            field=models.TextField(max_length=50, verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='model',
            field=models.TextField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Год релиза'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='spindle_speed',
            field=models.PositiveIntegerField(verbose_name='Скорость винта'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amount_of_DisplayPort',
            field=models.PositiveIntegerField(verbose_name='Количество портов DisplayPort'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amount_of_HDMI',
            field=models.PositiveIntegerField(verbose_name='Количество портов HDMI'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amount_of_USB',
            field=models.PositiveIntegerField(verbose_name='Количество портов USB'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amount_of_VGA',
            field=models.PositiveIntegerField(verbose_name='Количество портов VGA'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amount_of_slots_for_RAM',
            field=models.PositiveIntegerField(verbose_name='Количество слотов памяти'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='computer_id',
            field=models.ManyToManyField(related_name='related_MotherBoard', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.TextField(max_length=50, verbose_name='Форм-фактор'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='manufacturer',
            field=models.TextField(max_length=50, verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='max_speed_of_RAM',
            field=models.PositiveIntegerField(verbose_name='Максимальная частота памяти'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='model',
            field=models.TextField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_type',
            field=models.TextField(max_length=50, verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Год релиза'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.TextField(max_length=50, verbose_name='Сокет'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='computer_id',
            field=models.ManyToManyField(related_name='related_PowerBlock', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='form_factor',
            field=models.TextField(max_length=50, verbose_name='Форм-фактор'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='kpd',
            field=models.PositiveIntegerField(verbose_name='КПД'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='manufacturer',
            field=models.TextField(max_length=50, verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='model',
            field=models.TextField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='motherboard_power',
            field=models.TextField(max_length=50, verbose_name='Питание платы'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='power',
            field=models.PositiveIntegerField(verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Год релиза'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Емкость'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='computer_id',
            field=models.ManyToManyField(related_name='related_RAM', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='manufacturer',
            field=models.TextField(max_length=50, verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='model',
            field=models.TextField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='number_of_modules',
            field=models.PositiveIntegerField(verbose_name='Количество модулей'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_speed',
            field=models.PositiveIntegerField(verbose_name='Частота памяти'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_technology',
            field=models.TextField(max_length=50, verbose_name='Технология'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Год релиза'),
        ),
    ]
