# Generated by Django 3.2 on 2021-05-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210502_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='computer_id',
            field=models.ManyToManyField(null=True, related_name='related_Case', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='depth',
            field=models.PositiveIntegerField(verbose_name='Глубина, мм'),
        ),
        migrations.AlterField(
            model_name='case',
            name='height',
            field=models.PositiveIntegerField(verbose_name='Высота, мм'),
        ),
        migrations.AlterField(
            model_name='case',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Ширина, мм'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='CPU_speed',
            field=models.PositiveIntegerField(verbose_name='Частота, Гц'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='CPU_turbo_speed',
            field=models.PositiveIntegerField(verbose_name='Максимальная тактовая частота, Гц'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='L3_Cache',
            field=models.PositiveIntegerField(verbose_name='Кэш, Мб'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='computer_id',
            field=models.ManyToManyField(null=True, related_name='related_CPU', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='VRAM',
            field=models.PositiveIntegerField(verbose_name='Видеопамять, Гб'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='computer_id',
            field=models.ManyToManyField(null=True, related_name='related_GPU', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='effective_speed',
            field=models.PositiveIntegerField(verbose_name='Эффетивная частота, '),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='recommended_power',
            field=models.PositiveIntegerField(verbose_name='Рекомендуемая можность БП, Вт'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='cache',
            field=models.PositiveIntegerField(verbose_name='Кэш, Мб'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Емкость, Тб'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='computer_id',
            field=models.ManyToManyField(null=True, related_name='related_HDD', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='spindle_speed',
            field=models.PositiveIntegerField(verbose_name='Скорость винта, об/мин'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='computer_id',
            field=models.ManyToManyField(null=True, related_name='related_MotherBoard', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='max_speed_of_RAM',
            field=models.PositiveIntegerField(verbose_name='Максимальная частота памяти, ГГц'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='computer_id',
            field=models.ManyToManyField(null=True, related_name='related_PowerBlock', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='kpd',
            field=models.PositiveIntegerField(max_length=100, verbose_name='КПД, %'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='power',
            field=models.PositiveIntegerField(verbose_name='Мощность, Вт'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Емкость, Гб'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='computer_id',
            field=models.ManyToManyField(null=True, related_name='related_RAM', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_speed',
            field=models.PositiveIntegerField(verbose_name='Частота памяти, Ггц'),
        ),
    ]
