# Generated by Django 3.2 on 2021-05-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210502_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='case',
            name='computer_id',
            field=models.ManyToManyField(blank=True, related_name='related_Case', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='CPU_speed',
            field=models.PositiveIntegerField(verbose_name='Частота, МГц'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='CPU_turbo_speed',
            field=models.PositiveIntegerField(verbose_name='Максимальная тактовая частота, МГц'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='computer_id',
            field=models.ManyToManyField(blank=True, related_name='related_CPU', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='computer_id',
            field=models.ManyToManyField(blank=True, related_name='related_GPU', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='effective_speed',
            field=models.PositiveIntegerField(verbose_name='Эффетивная частота МГц, '),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='computer_id',
            field=models.ManyToManyField(blank=True, related_name='related_HDD', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='spindle_speed',
            field=models.PositiveIntegerField(verbose_name='Скорость винта, обр/мин'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amount_of_DisplayPort',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество портов DisplayPort'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amount_of_HDMI',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество портов HDMI'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amount_of_USB',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество портов USB'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amount_of_VGA',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество портов VGA'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='computer_id',
            field=models.ManyToManyField(blank=True, related_name='related_MotherBoard', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='max_speed_of_RAM',
            field=models.PositiveIntegerField(verbose_name='Максимальная частота памяти, МГц'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='computer_id',
            field=models.ManyToManyField(blank=True, related_name='related_PowerBlock', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='powerblock',
            name='kpd',
            field=models.PositiveIntegerField(verbose_name='КПД, %'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='computer_id',
            field=models.ManyToManyField(blank=True, related_name='related_RAM', to='mainapp.Computer'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_speed',
            field=models.PositiveIntegerField(verbose_name='Частота памяти, МГц'),
        ),
    ]
